### ISSUE TITLE
new domain requested 

### ISSUE THREAD

**Issue by Licolnlee** [neodevpro/neodevhost#11]
There is some domain in [this link](https://dn-davetech.qbox.me/A4V2luAi3.js),is it possible to add this ad domain list to your adblocklist?
Thanks for the efforts!
Great work here!

**Comment by FusionPlmH** [comment]
刚刚看到你的连接了，里面的domain是你自己抓的吗？

**Comment by Licolnlee** [comment]
> 刚刚看到你的连接了，里面的domain是你自己抓的吗？

Yes,it is.

**Comment by FusionPlmH** [comment]
just send an email via your mail box

**Comment by FusionPlmH** [comment]
Which link do you prefer 
https://raw.githubusercontent.com/Licolnlee/blog-cloud-storage/master/adblock.txt
or
https://licolnlee.icu/blog-cloud-storage/adblock.txt

**Comment by Licolnlee** [comment]
> Which link do you prefer 
> 
> https://raw.githubusercontent.com/Licolnlee/blog-cloud-storage/master/adblock.txt
> 
> or
> 
> https://licolnlee.icu/blog-cloud-storage/adblock.txt

The next one is better for mainland China users to subscribe.

**Comment by FusionPlmH** [comment]
Now i just use github action to merge and create the list  
just your prefer for me both is ok ,  i will put itto my readme .

**Comment by Licolnlee** [comment]
> Now i just use github action to merge and create the list  
> 
> just your prefer for me both is ok ,  i will put itto my readme .

ok，thank youfor yourwork.

**Comment by FusionPlmH** [comment]
You also

**Comment by Licolnlee** [comment]
> You also
I have moved my previous domain list into a new [repo](https://github.com/Licolnlee/AdBlockList) in order to better usage for others,and added whitelist for your team to applied for.
The new links are as below:

## Ad domain list:

> [domain.txt](https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/domain.txt):`https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/domain.txt`


## Ad whitelist:

> [whitelist.txt](https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/whitelist.txt):`https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/whitelist.txt`

**Comment by FusionPlmH** [comment]
Ok , nice work . Thank you for your contribution on mainland china list . Properly your  work is most needed .

**Comment by FusionPlmH** [comment]
Sir , I have been notic that you merge a huge list of domain , some result on invalid "Domain," like this , this pattern may not work .

My recommandation is  create a simplelist and ultra list  , because Huge list of data will result on poor performance , may increase the delay

**Comment by FusionPlmH** [comment]
Also below  3 type of  error :     
 
- lisat.bizalisat.biz。  #ending
- ll.16881616.com:8905 # port
- og.b612kaji.comdomain,log.sina.cn  # comma 

Not a standed , seem your scripts has peoblem at all .

**Comment by FusionPlmH** [comment]
At this stage , i will comment your list first until you able to fix it . Feel free to let me know  
👍

**Comment by Licolnlee** [comment]
> Sir , I have been notic that you merge a huge list of domain , some result on invalid "Domain," like this , this pattern may not work .
> 
> 
> 
> My recommandation is  create a simplelist and ultra list  , because Huge list of data will result on poor performance , may increase the delay
> 
> 

It’s my mistake.I accidentally merge adtest list to the domain.txt.I will correct it later.

**Comment by Licolnlee** [comment]
> Also below  3 type of  error :     
> 
>  
> 
> - lisat.bizalisat.biz。  #ending
> 
> - ll.16881616.com:8905 # port
> 
> - og.b612kaji.comdomain,log.sina.cn  # comma 
> 
> 
> 
> Not a standed , seem your scripts has problem at all .

Ok.Thank you for your work.I will recheck my list.

**Comment by Licolnlee** [comment]
> At this stage , i will comment your list first until you able to fix it . Feel free to let me know
> 👍

Thank you for pointing out my mistakes. I have rechecked my domain list.Now it will be okay.

**Comment by FusionPlmH** [comment]
Gotcha

**Comment by Potterli20** [comment]
whitelist:
https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/whitelist/master/domains.list
https://raw.githubusercontent.com/vokins/yhosts/master/whitelist.txt
https://raw.githubusercontent.com/WildcardTech/Filter-Domain-List/master/whitelist.txt
