### ISSUE TITLE
請求白名單

### ISSUE THREAD

**Issue by tasi788** [neodevpro/neodevhost#14]
**Describe the bug**
`www.taiwanlottery.com.tw ` 台灣公益彩券網頁被誤判。

**Expected behavior**
應該被加入白名單內。

**Additional context**
此為台灣合法經營非詐騙。
ref from [wiki](https://zh.wikipedia.org/zh-tw/%E5%8F%B0%E7%81%A3%E5%BD%A9%E5%88%B8)

**Comment by FusionPlmH** [comment]
已加入
