### ISSUE TITLE
blocklists hosts

### ISSUE THREAD

**Issue by Potterli20** [neodevpro/neodevhost#15]
Unified hosts + fakenews + gambling + porn + social:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
adaway:
https://adaway.org/hosts.txt

**Comment by FusionPlmH** [comment]
adaway is include in one of the list ， and for stevenblack，gambling porn social fakenews still some of the people need it ， so I keep it as default unified host
