### ISSUE TITLE
Allow: fls-na.amazon.com

### ISSUE THREAD

**Issue by bestpika** [neodevpro/neodevhost#16]
阻擋 `fls-na.amazon.com` 會影響 Amazon Kindle 登入及驗證購買項目
請把他放到白名單，謝謝

**Comment by FusionPlmH** [comment]
請問這個domain你已經測試了嗎？因為我手上沒amazon kindle.如果測試ok的話我稍後加入

**Comment by bestpika** [comment]
已經測試過了，這個域名放白名單才能正常登入

**Comment by FusionPlmH** [comment]
已加入白名單

**Comment by FusionPlmH** [comment]
同步到ｈｏｓｔ
