### ISSUE TITLE
After download host-dnsmasq.conf,can't restart dnsmasq.service

### ISSUE THREAD

**Issue by NBSOD** [neodevpro/neodevhost#19]
**Describe the bug**

After download host-dnsmasq.conf,can't restart dnsmasq.service

**Expected behavior**

This is log after dnsmasq restart failed

Aug 19 20:04:26 ntpserver kernel: dnsmasq[23007]: segfault at 0 ip 00007fd39724c641 sp 00007fff357bb458 error 4 in libc-2.17.so[7fd3970dd000+1c3000]
Aug 19 20:04:26 ntpserver systemd: dnsmasq.service: main process exited, code=killed, status=11/SEGV
Aug 19 20:04:26 ntpserver systemd: Unit dnsmasq.service entered failed state.
Aug 19 20:04:26 ntpserver systemd: dnsmasq.service failed.

**Desktop (please complete the following information):**

 - OS: [CentOS7]

**Additional context**
I start test and when i remark some line like this **address=/://.012345b.xyz/0.0.0.0** dnsmasq is restart successful. 
this is the link i download https://raw.githubusercontent.com/neodevpro/neodevhost/master/host_dnsmasq.conf

**Comment by NBSOD** [comment]
...淦，大佬懂中文啊。。。问题就是我直接把下载的host_dnsmasq.conf应用于我的dnsmasq之后导致service无法启动，启动后立马关闭。我在你的文件中注释掉这种**address=/://.012345b.xyz/0.0.0.0**地址就可以了

**Comment by NBSOD** [comment]
`://.`
`@@`
这两个符号是正则表达式么

**Comment by FusionPlmH** [comment]
谢谢啦，我也刚刚发现，修复了会告诉你

**Comment by FusionPlmH** [comment]
已经修复好了，重新按raw下载就可以，国内加速下载的连接会迟一个小时更新
