### ISSUE TITLE
Whitelist that should be added

### ISSUE THREAD

**Issue by Stright** [neodevpro/neodevhost#22]
**Is your feature request related to a problem? Please describe.**
No, I just think that this should be added.

**Describe the solution you'd like**
This is really good whitelist and it should be included.
Here is the whitelist: https://gitlab.com/Shub_/whitelist/-/raw/master/Whitelist

**Comment by FusionPlmH** [comment]
I think we don't need a huge list of whitelist , actually compare with blocked ,just only 100 around , and mostly is working properly . So I think maybe not add it at the moment

**Comment by Stright** [comment]
That’s completely fine and I totally understand ~ I’ll close the issue.

**Comment by FusionPlmH** [comment]
> That’s completely fine and I totally understand ~ I’ll close the issue.

just feel free to report any blocked that may Affect you
