### ISSUE TITLE
bbs.nga.cn 被误杀

### ISSUE THREAD

**Issue by JunTsao** [neodevpro/neodevhost#23]
此论坛匹配到了两条过滤规律规则
分别是：
g1.tagic.cn 
bdtj.tagtic.cn

当同时匹配并拦截时，NGA会卡住无法加载网页，需要F5刷新（每一次浏览都需要F5)
建议参考：https://github.com/privacy-protection-tools/anti-AD/issues/266#issuecomment-717662402

**Comment by FusionPlmH** [comment]
上述問題應該已經解決了的，不需要在我這邊修改

**Comment by FusionPlmH** [comment]
你可以更新測試看看

**Comment by JunTsao** [comment]
非常感谢！
