### ISSUE TITLE
东方财富和天天基金的走势图直接给屏蔽了

### ISSUE THREAD

**Issue by mustssr** [neodevpro/neodevhost#25]
RT

**Comment by FusionPlmH** [comment]
> RT
你好可以发一张截图和网站给我看看吗
我下面这里看到没有问题
![註解 2020-12-26 134934](https://user-images.githubusercontent.com/16817768/103152592-8c6c4500-47c4-11eb-9bd7-559f9598ee29.png)

**Comment by mustssr** [comment]
![K1.jpg](https://i.loli.net/2020/12/28/siAjkqNmZLuC1aM.jpg)
![2.jpg](https://i.loli.net/2020/12/28/NuYFanZtSk6Kwcg.jpg)
上开规则，下关规则

**Comment by FusionPlmH** [comment]
`push2.eastmoney.com`
应该是这个导致的，现在已经同步更新，你刷新更新下adguard的名单试一下

**Comment by mustssr** [comment]
> `push2.eastmoney.com`
> 应该是这个导致的，现在已经同步更新，你刷新更新下adguard的名单试一下

好了不拦截了

**Comment by FusionPlmH** [comment]
> > `push2.eastmoney.com`
> > 应该是这个导致的，现在已经同步更新，你刷新更新下adguard的名单试一下
> 
> 好了不拦截了

你看看還有其他問題嗎，沒有我過幾天就關issue了
