### ISSUE TITLE
网易云音乐貌似有些 API 地址被屏蔽了

### ISSUE THREAD

**Issue by rampageX** [neodevpro/neodevhost#26]
UnblockNeteaseMusic 启动直接出错， 0.0.0.0:80 连接被拒绝，AdGuard Home 关掉这个 hosts 就好了。

**Comment by FusionPlmH** [comment]
> UnblockNeteaseMusic 启动直接出错， 0.0.0.0:80 连接被拒绝，AdGuard Home 关掉这个 hosts 就好了。

可以麻烦你检测一下你adguard home 查询记录看看是哪些地址被屏蔽吗？ 因为我不在国内不方便使用这个应用程式

**Comment by rampageX** [comment]
httpdns.n.netease.com

![2020-12-27_150437](https://user-images.githubusercontent.com/994081/103165599-f7fdf300-4854-11eb-975e-ba85b66752d6.png)

**Comment by FusionPlmH** [comment]
你更新了最新的那个版本吗？你刷新看看，这个我昨天应该修复了

**Comment by rampageX** [comment]
OK了

**Comment by FusionPlmH** [comment]
有其他問題歡迎提出我會盡快修復
