### ISSUE TITLE
gleam.io login

### ISSUE THREAD

**Issue by xiao-mantou** [neodevpro/neodevhost#27]
<img width="400" src="https://user-images.githubusercontent.com/25640395/103131790-0d7aed80-469a-11eb-8869-f60194101930.png">
<img width="400" src="https://user-images.githubusercontent.com/25640395/103131792-14096500-469a-11eb-8925-3b6df3ff8a01.png">

[gleam.io](https://gleam.io/login)

```
https://js.gleam.io?
```

**Comment by FusionPlmH** [comment]
> <img alt="" width="400" src="https://user-images.githubusercontent.com/25640395/103131790-0d7aed80-469a-11eb-8869-f60194101930.png">
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/25640395/103131792-14096500-469a-11eb-8925-3b6df3ff8a01.png">
> 
> [gleam.io](https://gleam.io/login)
> 
> ```
> https://js.gleam.io?
> ```

I have update your request and update the list ， please see still have any other problem
