### ISSUE TITLE
网易云 360 迅雷 误报

### ISSUE THREAD

**Issue by sxx1314** [neodevpro/neodevhost#28]
## 网易云误报：
- 第一个是httpdns域名，拦截之后无法查询歌曲链接，影响网易云灰色工具等解锁。
```
httpdns.n.netease.com
```
- 第二个是app内的请求域名，拦截之后无法刷新歌单以及外部图片等
```
mr.da.netease.com
```

## 360误报
更新的有点牛逼，以前是360.cn的一些广告子域名拦截。这一次直接把整个360.cn给屏蔽了。影响各种软硬件使用，虽然大家都讨厌流氓数字。但是介于数字在天朝的影响力以及部分硬件要正常使用也必须使用360的域名。
下面罗列一些我加白的数字域名

- 360的开放api 影响基于360账户的第三方网站登录，如某安信。
```
openapi.360.cn
```
- 360的路由器app
```
captcha.360.cn
luyou.360.cn
jf.360.cn
iwifi.360.cn
```

## 迅雷比较奇葩  直接把下载域名屏蔽了 建议加白
```
down.sandai.net
```

**Comment by FusionPlmH** [comment]
> ## 网易云误报：
> * 第一个是httpdns域名，拦截之后无法查询歌曲链接，影响网易云灰色工具等解锁。
> 
> ```
> httpdns.n.netease.com
> ```
> 
> * 第二个是app内的请求域名，拦截之后无法刷新歌单以及外部图片等
> 
> ```
> mr.da.netease.com
> ```
> 
> ## 360误报
> 更新的有点牛逼，以前是360.cn的一些广告子域名拦截。这一次直接把整个360.cn给屏蔽了。影响各种软硬件使用，虽然大家都讨厌流氓数字。但是介于数字在天朝的影响力以及部分硬件要正常使用也必须使用360的域名。
> 下面罗列一些我加白的数字域名
> 
> * 360的开放api 影响基于360账户的第三方网站登录，如某安信。
>   openapi.360.cn
> * 360的路由器app
>   captcha.360.cn
>   luyou.360.cn
>   jf.360.cn
>   iwifi.360.cn
> * 迅雷比较奇葩  直接把下载域名屏蔽了 建议加白
>   down.sandai.net

十分感谢你提供的信息，这边刚刚也实测了下，已经同时把上面的名单同步更新了，可以尝试刷新下名单看看是否恢复正常。
