### ISSUE TITLE
百度智能云登录被屏蔽了

### ISSUE THREAD

**Issue by mustssr** [neodevpro/neodevhost#30]
https://login.bce.baidu.com/
百度智能云登录被屏蔽了
![01.png](https://i.loli.net/2021/01/13/1nyelkfSO6M4qRb.png)
![03.jpg](https://i.loli.net/2021/01/13/3CFGXtdPkHzSnZU.jpg)
RT

**Comment by FusionPlmH** [comment]
你这个是adblock模式
百度智能云登录被封锁基于 bce.baidu.com
在浏览器打bce.baidu.com后直接跳转去cloud.baidu.com
不过问题不大，算误杀
你可以更新看看
