### ISSUE TITLE
【误杀？】CNNIC官网

### ISSUE THREAD

**Issue by ron159** [neodevpro/neodevhost#31]
今天查看《中国互联网络发展状况统计报告》时，无法访问，查看列表发现以下网址被屏蔽：
```
www.cnnic.net.cn
cnnic.net.cn
```
请问这个是有意还是误杀呢？

**Comment by FusionPlmH** [comment]
首先这个是无意封杀的，并不是本人意愿。这个问题是来源于上游源码[neohosts](https://github.com/neoFelhz/neohosts)的封杀，我这边将会对这个进行评估。

**Comment by ron159** [comment]
去那边看了一下，应该是由于
- CNNIC 根证书劫持
这个问题所以屏蔽了CNNIC的官网
不过目前这两个地址都是http，不再存在之前的问题

可以参考另外一个项目的相关讨论：https://github.com/privacy-protection-tools/anti-AD/issues/274

**Comment by FusionPlmH** [comment]
今晚我回去看看详情继续找找相关资料

**Comment by ron159** [comment]
> 今晚我回去看看详情继续找找相关资料

感谢！

**Comment by FusionPlmH** [comment]
@ron159 不用客氣

**Comment by FusionPlmH** [comment]
已经whitelist
