### ISSUE TITLE
开了Full模式之后 给娃买的洪恩教育登不上

### ISSUE THREAD

**Issue by Sir-Speed-a-Lot** [neodevpro/neodevhost#34]
在ssrp里面开了Full模式之后 给娃买的洪恩教育登不上 lite模式就没问题
说ping服务器连接失败 不知是不是地址被误屏蔽

如图
https://photos.app.goo.gl/BngoBNJJMCSen3nJ8

**Comment by FusionPlmH** [comment]
问题未知
