### ISSUE TITLE
请问白名单是哪个文件，customallowlist还是checkallow？

### ISSUE THREAD

**Issue by WoChen5770** [neodevpro/neodevhost#36]
我使用的是adh。
多谢

**Comment by FusionPlmH** [comment]
两个都是

**Comment by WoChen5770** [comment]
> 两个都是

好的，我也是把这两个都加到adguardhome的白名单里了

**Comment by FusionPlmH** [comment]
或者你用lite 精简版就

**Comment by WoChen5770** [comment]
> 或者你用lite 精简版就行了

lite_adblocker？我目前用的就是这个，可这个里还是把edge.activity.windows.com给屏蔽了，所以我得加个白名单列表

**Comment by FusionPlmH** [comment]
> > 或者你用lite 精简版就行了
> 
> lite_adblocker？我目前用的就是这个，可这个里还是把edge.activity.windows.com给屏蔽了，所以我得加个白名单列表

这个已经修复了

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/118075400-86c57380-b3e2-11eb-9e9a-fd34304cdeec.png)

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/118075444-95ac2600-b3e2-11eb-97ca-c4005f5ea600.png)

**Comment by WoChen5770** [comment]
> > > 或者你用lite 精简版就行了
> > 
> > 
> > lite_adblocker？我目前用的就是这个，可这个里还是把edge.activity.windows.com给屏蔽了，所以我得加个白名单列表
> 
> 这个已经修复了

还是拦截了

**Comment by FusionPlmH** [comment]
个人建议用host文件，adb格式。因为host文件针对单一网站拦截最好，adb格式会通杀了很多。

**Comment by FusionPlmH** [comment]
> > 或者你用lite 精简版就行了
> 
> lite_adblocker？我目前用的就是这个，可这个里还是把edge.activity.windows.com给屏蔽了，所以我得加个白名单列表

用这个： https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_host

**Comment by WoChen5770** [comment]
> > > 或者你用lite 精简版就行了
> > 
> > 
> > lite_adblocker？我目前用的就是这个，可这个里还是把edge.activity.windows.com给屏蔽了，所以我得加个白名单列表
> 
> 用这个： https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_host

好的，我试试看
