### ISSUE TITLE
麻烦加入创维酷开电视系统的广告地址

### ISSUE THREAD

**Issue by simonchan6688** [neodevpro/neodevhost#37]
如下：
0.0.0.0 log.skysrt.com
0.0.0.0 passport.coocaa.com
0.0.0.0 movie.tc.skysrt.com
0.0.0.0 sky.t003.ottcn.com
0.0.0.0 api.hoisin.hw.coocaatv.com
0.0.0.0 hoisin.coocaatv.com
0.0.0.0 active.tc.skysrt.com
0.0.0.0 api.tvinfo.skysrt.com
0.0.0.0 member.coocaa.com
0.0.0.0 api.upgrade.skysrt.com/tv
0.0.0.0 pay.coocaa.com
0.0.0.0 push.skysrt.com
0.0.0.0 tc.skysrt.com
0.0.0.0 sky.tvos.skysrt.com
0.0.0.0 api.app.skysrt.com
0.0.0.0 webapp.skysrt.com
0.0.0.0 api.device.skysrt.com
0.0.0.0 api.device.hw.skysrt.com
0.0.0.0 api.upgrade.skysrt.com
0.0.0.0 update01.skyworth-cloud.com
0.0.0.0 update01.skyworth-cloud.com.wswebpic.com
0.0.0.0 res.hoisin.coocaatv.com
0.0.0.0 sky.fs.skysrt.com
0.0.0.0 apk.sky.fs.skysrt.com

**Comment by FusionPlmH** [comment]
好的

**Comment by FusionPlmH** [comment]
已经添加
