### ISSUE TITLE
直接阻止整个 com 域并不合适

### ISSUE THREAD

**Issue by xz-dev** [neodevpro/neodevhost#44]
**Describe the bug**
`||com^` 会导致大范围误杀

**Desktop (please complete the following information):**
 - OS: AdGuard Home
 - Version v0.106.3

**Comment by SODAGARY** [comment]
今天发现绝大多数网页打不开，检查后发现是AdGuard Home里NEO过滤的问题，不知道这么大范围的误杀是出现了什么问题

**Comment by xz-dev** [comment]
> 今天发现绝大多数网页打不开，检查后发现是AdGuard Home里NEO过滤的问题，不知道这么大范围的误杀是出现了什么问题

https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker
中间有一行规则为 `||com^`

**Comment by SupernovaCooper** [comment]
果然是Neo的问题。。。家里一天死活上不了网，回家排查了一圈，确定是AdGuard Home的问题，最后发现关了Neo规则就好好的了。大佬啊，不要这样搞我啊。

**Comment by trotack** [comment]
同被搞死+1

**Comment by FusionPlmH** [comment]
![image](https://user-images.githubusercontent.com/16817768/141795144-1d5f289a-142c-42e8-9275-ff9878e771a8.png)
修了
