### ISSUE TITLE
||com^ 导致大范围误杀

### ISSUE THREAD

**Issue by SODAGARY** [neodevpro/neodevhost#47]
刚刚家里网络突然用不了，检查了一顿设备问题之后发现是NEO过滤器的问题，还是发现了||com^ 这条

**Comment by FusionPlmH** [comment]
你尽量选择host 或者 domain格式。adb格式封杀太严重，我也容易出错，稍后马上解决。

**Comment by FusionPlmH** [comment]
已经修好轮子
2a7dfd1c0fa3f187d04fd7eabed9ff0b6ae23df2
