### ISSUE TITLE
白名单 com

### ISSUE THREAD

**Issue by DoingDog** [neodevpro/neodevhost#52]
https://github.com/neodevpro/neodevhost/blob/827181c7ead8ec89cc7b2ef35704101b350218bd/customallowlist#L10

这行有明显问题吧

**Comment by FusionPlmH** [comment]
这没问题说实话，因为有个鸡巴域名透过脚本跑后会变成com。要是adb用了规则就会把com全封了

**Comment by DoingDog** [comment]
好吧
