### ISSUE TITLE
误杀及错误更正

### ISSUE THREAD

**Issue by hnyyghk** [neodevpro/neodevhost#55]
https://raw.githubusercontent.com/neodevpro/neodevhost/master/smartdns.conf
中的address /api.xiaomi.com/#由于前缀匹配会导致米家全能扫拖机器人获取不到地图列表cnbj2.fds.api.xiaomi.com
nslookup api.xiaomi.com发现子域名已经没有dns记录，应该可以去除了

还有三条规则
address /::1localhost/#
address /XiaoQiang/#
address /inf/#
看起来并不是域名..

**Comment by FusionPlmH** [comment]
已更正

**Comment by hnyyghk** [comment]
address /inf/#

这一条规则发现还是在

**Comment by FusionPlmH** [comment]
c6dd36feb5f6011357bfef4216cd99472593f082

**Comment by hnyyghk** [comment]
address /inf/#


刚更新的fa9db9359b1f6a260dbafd360dd7fc57c8e74a81发现又出现了address /inf/#

**Comment by FusionPlmH** [comment]
a11ff837470eecd046e991a7a9baaf05bc58b1be

这次应该真修好了
