### ISSUE TITLE
站点误报

### ISSUE THREAD

**Issue by QuantumzzZ** [neodevpro/neodevhost#56]
maimai.cn 误报

**Comment by QuantumzzZ** [comment]
职业吹水论坛的域名 套用规则后脉脉app无法使用

**Comment by FusionPlmH** [comment]
[](url)

**Comment by FusionPlmH** [comment]
https://github.com/neodevpro/neodevhost/commit/d5c04b0659fef799cbd3b8994234f7f4b24618cd
