### ISSUE TITLE
开启后饿了么无法使用

### ISSUE THREAD

**Issue by mustssr** [neodevpro/neodevhost#57]
关闭后正常
 Title: NEO DEV HOST
 Power By NEO DEV Team
 Project home page: https://github.com/neodevpro/neodevhost
 Last update: 2022-06-19

<a href="https://sm.ms/image/pwGvSFo4OiWxlUY" target="_blank"><img src="https://s2.loli.net/2022/06/20/pwGvSFo4OiWxlUY.jpg" /></a>
<a href="https://sm.ms/image/mGc8ifxy5SrwKp7" target="_blank"><img src="https://s2.loli.net/2022/06/20/mGc8ifxy5SrwKp7.jpg" /></a>

**Comment by FusionPlmH** [comment]
源是最新的吗？刷新一下源看看

**Comment by mustssr** [comment]
<a href="https://sm.ms/image/EohLs9Uqvt4zZDa" target="_blank"><img src="https://s2.loli.net/2022/06/20/EohLs9Uqvt4zZDa.jpg" alt="屏幕截图 2022-06-20 134725.jpg"></a>
大概必要解析被 ||tanx.com^ 拦截了把

**Comment by mustssr** [comment]
可以了
