### ISSUE TITLE
误杀 miui 知乎小程序

### ISSUE THREAD

**Issue by catsimple** [neodevpro/neodevhost#63]
从小米浏览器加载任意知乎网站，弹出知乎小程序，无法显示内容
![Screenshot_2022-11-15-09-37-17-143_com android browser](https://user-images.githubusercontent.com/23014926/201806386-e439b5fe-e03d-4120-854a-a6b579a452f9.jpg)
经排查与sugar.zhihu.com被拦截有关

**Comment by FusionPlmH** [comment]
已經解決，請查看
