### ISSUE TITLE
jnn-pa.googleapis.com 导致YouTube视频播放一分钟停止？

### ISSUE THREAD

**Issue by PikuZheng** [neodevpro/neodevhost#88]
smartdns 和 nextdns 都有反馈自7月1日起如果屏蔽了 jnn-pa.googleapis.com 会导致部分视频在播放1分钟后停止。稍微查了一下adb和ublock都没有屏蔽这个域名。问问大家有没有遇到相同情况的？

**Comment by FusionPlmH** [comment]
經過檢查，這是 YouTube 和 YouTube iframe 的一部分。確認會影響。已經修正
